### ISSUE TITLE
Extend session does not work when there is an open dialog in the application

### ISSUE THREAD

**Issue by sujoykd** [vaadin-component-factory/idle-notification#11]
The extend session functionality does not work when the application has an open dialog and the idle-notification popup opens on top of it.

On clicking the "extend session" button nothing happens.

The idle-notification component that opens a dialog which has a button that calls a @ClientCallable method 'pokeServer'.
This works as usual. However, if there is another dialog open in the application and the idle-notification opens its dialog on top of it, then this @ClientCallable method is not invoked.

This is what I can see in the browser console when it works,
`FlowClient.js:205 Received xhr message: for(;;);[{"syncId":2,"clientId":2,"execute":[[0,true,[0,4],"return (function() { this.$server['}p']($0, true, $1)}).apply($2)"]],"timings":[495,0]}]`

and, this is what happens when there is another dialog open in the application and the idle-notification opens on top of it. This is what I can see in the browser console on clicking the "extend session" button,
`FlowClient.js:205 Received xhr message: for(;;);[{"syncId":4,"clientId":4,"timings":[466,1]}]`

Note this happens in v2.0.0 with Vaadin 23.3.1

**Comment by TatuLund** [comment]
It could be that server side modality feature of the Dialog blocks the event.

If so, the workaround is to disable Dialog's server side modality 

`ui.setChildComponentModal(dialog, false);`

**Comment by sujoykd** [comment]
Using ui.setChildComponentModal(dialog, false); in either dialogs or the idle-notification or both does not seem to work.

If the application has the dialogs like this,
```
public HelloWorldView() {
    var name = new TextField("Your name");
    var sayHello = new Button("Say hello");
    sayHello.addClickListener(e -> {
        openDialog("first");
        openDialog("second");
        openDialog("third");
    });
    setMargin(true);
    setVerticalComponentAlignment(Alignment.END, name, sayHello);
    
    add(name, sayHello);
}
    
private void openDialog(String text) {
    Dialog dialog = new Dialog(new Span(text));
    dialog.add(new Button("close " + text, ev -> dialog.close()));
    dialog.setDraggable(true);
    dialog.setCloseOnOutsideClick(false);
    dialog.open();

    // added later as suggested in the comment above
    UI.getCurrent().setChildComponentModal(dialog, false);
}
```

and this is how the Idle-Notification is added in the MainLayout

```
public MainLayout() {
    idleNotification();
}
    
private void idleNotification() {
    IdleNotification idleNotification = new IdleNotification();
    idleNotification.setSecondsBeforeNotification(1790);
    idleNotification.setMessage("Your session will expire in " + IdleNotification.MessageFormatting.SECS_TO_TIMEOUT + " seconds. Total duration is "
            + IdleNotification.MessageFormatting.SECS_MAX_IDLE_TIMEOUT);
    idleNotification.addExtendSessionButton("Extend session");
    idleNotification.addRedirectButton("Logout now", "logout");
    idleNotification.addCloseButton();
    idleNotification.setExtendSessionOnOutsideClick(true);
    idleNotification.addExtendSessionListener(event -> {
        System.out.println(event.getSource());
    });
    UI.getCurrent().add(idleNotification);

    // added later as suggested in the comment above
    UI.getCurrent().setChildComponentModal(idleNotification, false);
}
```

**Comment by TatuLund** [comment]
Version 2.0.1 has been released with the fix.
