### ISSUE TITLE
Flow 23 compatibility

### ISSUE THREAD

**Issue by oilhands** [vaadin-component-factory/idle-notification#7]
So, I'm interested in this component for Flow 23. I've dropped in the maven dependency and added some code to an onAttach method, but no luck getting it to work. Any plans for updating this? Maybe I need to do something special to get it to work with the newest version of Flow?

**Comment by osenbg** [comment]
We are also interested that it will work under Flow 23.

**Comment by TatuLund** [comment]
Version 2.0.0 is available now and supports Vaadin 23.
